# Generated by Django 4.1.3 on 2023-01-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books_blog', '0003_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=3000)),
                ('sent_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
